# -*- coding: utf-8 -*-
"""deep_stocks.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sgyhzEXvhTFELL_ozKQKWyYsmmcRA5Rn
"""

def deep_stocks(url):
    import datetime
    import requests
    from bs4 import BeautifulSoup
    import json
    import pandas as pd
    res=requests.get(url)
    soup=BeautifulSoup(res.content,features="html.parser")
    script_tag = soup.find("script", {"id": "__NEXT_DATA__"})
    if script_tag is None:
        print(f"No script tag with id '__NEXT_DATA__' found on {url}")
        return None
    json_data = json.loads(script_tag.string)
    security_info = json_data['props']['pageProps'].get('securityInfo',None)
    if security_info is None:
        print("No security info found.")
        return None
    isin = security_info.get('isin', None)
    value = security_info.get('ratios', {})
    details = json_data['props']['pageProps']['securityQuote']
    date_today = datetime.date.today().strftime('%Y-%m-%d')
    result_dict = {}
    result_dict.update({"Date":date_today,"ISIN":isin})
    result_dict.update(value)
    result_dict.update(details)
    df = pd.DataFrame(result_dict, index=[0])
    
    return df